/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatThreadIdNotesRouteImport } from './routes/_chat.$threadId.notes'
import { Route as ChatThreadIdDiffRouteImport } from './routes/_chat.$threadId.diff'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdNotesRoute = ChatThreadIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ChatThreadIdRoute,
} as any)
const ChatThreadIdDiffRoute = ChatThreadIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ChatThreadIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/$threadId/diff': typeof ChatThreadIdDiffRoute
  '/$threadId/notes': typeof ChatThreadIdNotesRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/$threadId/diff': typeof ChatThreadIdDiffRoute
  '/$threadId/notes': typeof ChatThreadIdNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$threadId/diff': typeof ChatThreadIdDiffRoute
  '/_chat/$threadId/notes': typeof ChatThreadIdNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/settings'
    | '/$threadId/diff'
    | '/$threadId/notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/$threadId' | '/settings' | '/' | '/$threadId/diff' | '/$threadId/notes'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/$threadId/diff'
    | '/_chat/$threadId/notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId/notes': {
      id: '/_chat/$threadId/notes'
      path: '/notes'
      fullPath: '/$threadId/notes'
      preLoaderRoute: typeof ChatThreadIdNotesRouteImport
      parentRoute: typeof ChatThreadIdRoute
    }
    '/_chat/$threadId/diff': {
      id: '/_chat/$threadId/diff'
      path: '/diff'
      fullPath: '/$threadId/diff'
      preLoaderRoute: typeof ChatThreadIdDiffRouteImport
      parentRoute: typeof ChatThreadIdRoute
    }
  }
}

interface ChatThreadIdRouteChildren {
  ChatThreadIdDiffRoute: typeof ChatThreadIdDiffRoute
  ChatThreadIdNotesRoute: typeof ChatThreadIdNotesRoute
}

const ChatThreadIdRouteChildren: ChatThreadIdRouteChildren = {
  ChatThreadIdDiffRoute: ChatThreadIdDiffRoute,
  ChatThreadIdNotesRoute: ChatThreadIdNotesRoute,
}

const ChatThreadIdRouteWithChildren = ChatThreadIdRoute._addFileChildren(
  ChatThreadIdRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
